### ISSUE TITLE
HDMI output - no display

### ISSUE THREAD

**Issue by anfractuosity** [Digilent/ZYBO#11]
Hi,

When I performed the synthesis and it generated the bitstream, I got the following warning:

```
 [Timing 38-249] Generated clock hdmi_out_i/rgb2dvi_0/U0/SerialClk has no logical paths from master clock axi_dynclk_0_PXL_CLK_O. [/home/chris/ZYBO/Projects/hdmi_out/proj/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_clocks.xdc:5]
Resolution: Review the path between the master clock and the generated clock with the schematic viewer and correct the -source option. If it is correct and the master clock does not have a timing path to the generated clock, define the generated clock as a primary clock by using create_clock.
```
I am using Vivado 2016.4

I was still able to program the Zybo though, but I seem to get no HDMI output, when I attach it to a TV.

I notice I only have /dev/ttyUSB1, am I supposed to have two devices, /dev/ttyUSB0 and /dev/ttyUSB1, where usb0, would be used for the uart, and usb1 for jtag?

Just wondering if anyone has any ideas?

Cheers
Chris

**Comment by sbobrowicz** [comment]
That warning is a minor bug and is not causing your problem.

Your problem will take some additional discussion to troubleshoot, and we are trying to reserve this space for bug tracking. Please post your question on our forum linked below and myself or someone else will work with you to figure this out. 

https://forum.digilentinc.com/forum/4-fpga/
