### ISSUE TITLE
DMA Audio Demo requires *two* Application Starts Before Audio is Available

### ISSUE THREAD

**Issue by preusser** [Digilent/ZYBO#9]
The DMA audio demo is working perfectly - once you have started the application for a second time from the SDK using _Run As -> Launch on Hardware (GDB)_ or _Debug As -> Launch on Hardware (GDB)_ **without a power cycle**. Taking a guess, the commands of the I2S initialization might be issued too quickly or in a slightly reversed order so that the SSM2603 device is left initialized only half way. The initialization is then completed in the second run so that the audio operates properly then.

**Comment by sbobrowicz** [comment]
Resolved by https://github.com/Digilent/ZYBO/commit/8befea8267591f25b39add81ad9d7b6afef330d3
Thanks preusser!
